# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditEvidenceDialog.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EditEvidenceDialog(object):
    def setupUi(self, EditEvidenceDialog):
        EditEvidenceDialog.setObjectName("EditEvidenceDialog")
        EditEvidenceDialog.resize(279, 309)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(EditEvidenceDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(EditEvidenceDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.evidenceTab = QtWidgets.QWidget()
        self.evidenceTab.setObjectName("evidenceTab")
        self.gridLayout = QtWidgets.QGridLayout(self.evidenceTab)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.evidenceTab)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.comboBox_assertion = QtWidgets.QComboBox(self.evidenceTab)
        self.comboBox_assertion.setObjectName("comboBox_assertion")
        self.gridLayout.addWidget(self.comboBox_assertion, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.evidenceTab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_eco = QtWidgets.QLabel(self.evidenceTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_eco.sizePolicy().hasHeightForWidth())
        self.label_eco.setSizePolicy(sizePolicy)
        self.label_eco.setText("")
        self.label_eco.setWordWrap(True)
        self.label_eco.setObjectName("label_eco")
        self.horizontalLayout_2.addWidget(self.label_eco)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_select_eco = QtWidgets.QPushButton(self.evidenceTab)
        self.pushButton_select_eco.setObjectName("pushButton_select_eco")
        self.horizontalLayout_2.addWidget(self.pushButton_select_eco)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.evidenceTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_term = QtWidgets.QWidget()
        self.page_term.setObjectName("page_term")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_term)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_term = QtWidgets.QLineEdit(self.page_term)
        self.lineEdit_term.setObjectName("lineEdit_term")
        self.verticalLayout_5.addWidget(self.lineEdit_term)
        self.stackedWidget.addWidget(self.page_term)
        self.page_link = QtWidgets.QWidget()
        self.page_link.setObjectName("page_link")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_link)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_link = QtWidgets.QLabel(self.page_link)
        self.label_link.setText("")
        self.label_link.setObjectName("label_link")
        self.horizontalLayout.addWidget(self.label_link)
        self.toolButton_select = QtWidgets.QToolButton(self.page_link)
        self.toolButton_select.setIconSize(QtCore.QSize(13, 13))
        self.toolButton_select.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.toolButton_select.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_select.setArrowType(QtCore.Qt.RightArrow)
        self.toolButton_select.setObjectName("toolButton_select")
        self.horizontalLayout.addWidget(self.toolButton_select)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.stackedWidget.addWidget(self.page_link)
        self.gridLayout.addWidget(self.stackedWidget, 3, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.evidenceTab)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.evidenceTab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_target = QtWidgets.QLabel(self.evidenceTab)
        self.label_target.setText("")
        self.label_target.setObjectName("label_target")
        self.horizontalLayout_3.addWidget(self.label_target)
        self.toolButton_select_targe = QtWidgets.QToolButton(self.evidenceTab)
        self.toolButton_select_targe.setIconSize(QtCore.QSize(13, 13))
        self.toolButton_select_targe.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.toolButton_select_targe.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_select_targe.setArrowType(QtCore.Qt.RightArrow)
        self.toolButton_select_targe.setObjectName("toolButton_select_targe")
        self.horizontalLayout_3.addWidget(self.toolButton_select_targe)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.tabWidget.addTab(self.evidenceTab, "")
        self.referenceTab = QtWidgets.QWidget()
        self.referenceTab.setObjectName("referenceTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.referenceTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.referenceWidget = ReferenceDisplayWidget(self.referenceTab)
        self.referenceWidget.setObjectName("referenceWidget")
        self.verticalLayout_3.addWidget(self.referenceWidget)
        self.tabWidget.addTab(self.referenceTab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.groupBox = QtWidgets.QGroupBox(EditEvidenceDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBox_comment = QtWidgets.QPlainTextEdit(self.groupBox)
        self.textBox_comment.setObjectName("textBox_comment")
        self.verticalLayout.addWidget(self.textBox_comment)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(EditEvidenceDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(EditEvidenceDialog)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(EditEvidenceDialog.accept)
        self.buttonBox.rejected.connect(EditEvidenceDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(EditEvidenceDialog)

    def retranslateUi(self, EditEvidenceDialog):
        _translate = QtCore.QCoreApplication.translate
        EditEvidenceDialog.setWindowTitle(_translate("EditEvidenceDialog", "Edit Evidence"))
        self.label_2.setText(_translate("EditEvidenceDialog", "Code:"))
        self.label.setText(_translate("EditEvidenceDialog", "Assertion:"))
        self.pushButton_select_eco.setText(_translate("EditEvidenceDialog", "Select"))
        self.toolButton_select.setText(_translate("EditEvidenceDialog", "Select"))
        self.comboBox.setItemText(0, _translate("EditEvidenceDialog", "Term:"))
        self.comboBox.setItemText(1, _translate("EditEvidenceDialog", "Link:"))
        self.label_3.setText(_translate("EditEvidenceDialog", "Target:"))
        self.toolButton_select_targe.setText(_translate("EditEvidenceDialog", "Select"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.evidenceTab), _translate("EditEvidenceDialog", "Evidence"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.referenceTab), _translate("EditEvidenceDialog", "References"))
        self.groupBox.setTitle(_translate("EditEvidenceDialog", "Comment"))

from GEMEditor.widgets.secondaryDialog import ReferenceDisplayWidget
