# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EvidenceAttributesDisplayWidget.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(210, 125)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox_assertion = QtWidgets.QComboBox(Form)
        self.comboBox_assertion.setObjectName("comboBox_assertion")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_assertion)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_target_2 = QtWidgets.QLabel(Form)
        self.label_target_2.setText("")
        self.label_target_2.setObjectName("label_target_2")
        self.horizontalLayout_4.addWidget(self.label_target_2)
        self.toolButton_select_targe_2 = QtWidgets.QToolButton(Form)
        self.toolButton_select_targe_2.setIconSize(QtCore.QSize(13, 13))
        self.toolButton_select_targe_2.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.toolButton_select_targe_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_select_targe_2.setArrowType(QtCore.Qt.RightArrow)
        self.toolButton_select_targe_2.setObjectName("toolButton_select_targe_2")
        self.horizontalLayout_4.addWidget(self.toolButton_select_targe_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_eco = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_eco.sizePolicy().hasHeightForWidth())
        self.label_eco.setSizePolicy(sizePolicy)
        self.label_eco.setText("")
        self.label_eco.setWordWrap(True)
        self.label_eco.setObjectName("label_eco")
        self.horizontalLayout_2.addWidget(self.label_eco)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_select_eco = QtWidgets.QPushButton(Form)
        self.pushButton_select_eco.setObjectName("pushButton_select_eco")
        self.horizontalLayout_2.addWidget(self.pushButton_select_eco)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.comboBox_link = QtWidgets.QComboBox(Form)
        self.comboBox_link.setObjectName("comboBox_link")
        self.comboBox_link.addItem("")
        self.comboBox_link.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.comboBox_link)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_term = QtWidgets.QWidget()
        self.page_term.setObjectName("page_term")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_term)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_term = QtWidgets.QLineEdit(self.page_term)
        self.lineEdit_term.setObjectName("lineEdit_term")
        self.verticalLayout_5.addWidget(self.lineEdit_term)
        self.stackedWidget.addWidget(self.page_term)
        self.page_link = QtWidgets.QWidget()
        self.page_link.setObjectName("page_link")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_link)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_link = QtWidgets.QLabel(self.page_link)
        self.label_link.setText("")
        self.label_link.setObjectName("label_link")
        self.horizontalLayout.addWidget(self.label_link)
        self.toolButton_select = QtWidgets.QToolButton(self.page_link)
        self.toolButton_select.setIconSize(QtCore.QSize(13, 13))
        self.toolButton_select.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.toolButton_select.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_select.setArrowType(QtCore.Qt.RightArrow)
        self.toolButton_select.setObjectName("toolButton_select")
        self.horizontalLayout.addWidget(self.toolButton_select)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.stackedWidget.addWidget(self.page_link)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.stackedWidget)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Assertion:"))
        self.label_3.setText(_translate("Form", "Target:"))
        self.toolButton_select_targe_2.setText(_translate("Form", "Select"))
        self.label_2.setText(_translate("Form", "Code:"))
        self.pushButton_select_eco.setText(_translate("Form", "Select"))
        self.comboBox_link.setItemText(0, _translate("Form", "Term:"))
        self.comboBox_link.setItemText(1, _translate("Form", "Link:"))
        self.toolButton_select.setText(_translate("Form", "Select"))

