# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MapDialog.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MapDialog(object):
    def setupUi(self, MapDialog):
        MapDialog.setObjectName("MapDialog")
        MapDialog.resize(724, 602)
        self.verticalLayout = QtWidgets.QVBoxLayout(MapDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(MapDialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.inputScaling = QtWidgets.QSpinBox(MapDialog)
        self.inputScaling.setMaximum(10000)
        self.inputScaling.setSingleStep(100)
        self.inputScaling.setProperty("value", 1000)
        self.inputScaling.setObjectName("inputScaling")
        self.horizontalLayout.addWidget(self.inputScaling)
        self.line = QtWidgets.QFrame(MapDialog)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.label = QtWidgets.QLabel(MapDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.inputXMargin = QtWidgets.QSpinBox(MapDialog)
        self.inputXMargin.setMaximum(5000)
        self.inputXMargin.setProperty("value", 300)
        self.inputXMargin.setObjectName("inputXMargin")
        self.horizontalLayout.addWidget(self.inputXMargin)
        self.line_2 = QtWidgets.QFrame(MapDialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(MapDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.inputYMargin = QtWidgets.QSpinBox(MapDialog)
        self.inputYMargin.setMaximum(5000)
        self.inputYMargin.setProperty("value", 300)
        self.inputYMargin.setObjectName("inputYMargin")
        self.horizontalLayout.addWidget(self.inputYMargin)
        self.line_3 = QtWidgets.QFrame(MapDialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.label_4 = QtWidgets.QLabel(MapDialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.inputIterations = QtWidgets.QSpinBox(MapDialog)
        self.inputIterations.setMinimum(1)
        self.inputIterations.setProperty("value", 50)
        self.inputIterations.setObjectName("inputIterations")
        self.horizontalLayout.addWidget(self.inputIterations)
        self.line_4 = QtWidgets.QFrame(MapDialog)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.label_5 = QtWidgets.QLabel(MapDialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.inputDistance = QtWidgets.QDoubleSpinBox(MapDialog)
        self.inputDistance.setMaximum(1.0)
        self.inputDistance.setSingleStep(0.1)
        self.inputDistance.setProperty("value", 0.1)
        self.inputDistance.setObjectName("inputDistance")
        self.horizontalLayout.addWidget(self.inputDistance)
        self.buttonDraw = QtWidgets.QPushButton(MapDialog)
        self.buttonDraw.setObjectName("buttonDraw")
        self.horizontalLayout.addWidget(self.buttonDraw)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.webView = QtWebEngineWidgets.QWebView(MapDialog)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.verticalLayout.addWidget(self.webView)
        self.buttonBox = QtWidgets.QDialogButtonBox(MapDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(MapDialog)
        self.buttonBox.accepted.connect(MapDialog.accept)
        self.buttonBox.rejected.connect(MapDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(MapDialog)

    def retranslateUi(self, MapDialog):
        _translate = QtCore.QCoreApplication.translate
        MapDialog.setWindowTitle(_translate("MapDialog", "Map"))
        self.label_3.setText(_translate("MapDialog", "scaling:"))
        self.label.setText(_translate("MapDialog", "x-margin:"))
        self.label_2.setText(_translate("MapDialog", "y-margin:"))
        self.label_4.setText(_translate("MapDialog", "iterations:"))
        self.label_5.setText(_translate("MapDialog", "distance:"))
        self.buttonDraw.setText(_translate("MapDialog", "redraw"))

from PyQt5 import QtWebEngineWidgets
