# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modelDisplayWidget.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_modelDisaplayWidget(object):
    def setupUi(self, modelDisaplayWidget):
        modelDisaplayWidget.setObjectName("modelDisaplayWidget")
        modelDisaplayWidget.resize(374, 357)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(modelDisaplayWidget.sizePolicy().hasHeightForWidth())
        modelDisaplayWidget.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(modelDisaplayWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.informationBox = QtWidgets.QGroupBox(modelDisaplayWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.informationBox.sizePolicy().hasHeightForWidth())
        self.informationBox.setSizePolicy(sizePolicy)
        self.informationBox.setObjectName("informationBox")
        self.gridLayout = QtWidgets.QGridLayout(self.informationBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_number_genes_description = QtWidgets.QLabel(self.informationBox)
        self.label_number_genes_description.setObjectName("label_number_genes_description")
        self.gridLayout.addWidget(self.label_number_genes_description, 5, 0, 1, 1)
        self.label_number_reactions = QtWidgets.QLabel(self.informationBox)
        self.label_number_reactions.setText("")
        self.label_number_reactions.setObjectName("label_number_reactions")
        self.gridLayout.addWidget(self.label_number_reactions, 4, 1, 1, 1)
        self.label_model_path = QtWidgets.QLabel(self.informationBox)
        self.label_model_path.setText("")
        self.label_model_path.setObjectName("label_model_path")
        self.gridLayout.addWidget(self.label_model_path, 0, 1, 1, 1)
        self.label_number_metabolites = QtWidgets.QLabel(self.informationBox)
        self.label_number_metabolites.setText("")
        self.label_number_metabolites.setObjectName("label_number_metabolites")
        self.gridLayout.addWidget(self.label_number_metabolites, 3, 1, 1, 1)
        self.label_number_reaction_description = QtWidgets.QLabel(self.informationBox)
        self.label_number_reaction_description.setObjectName("label_number_reaction_description")
        self.gridLayout.addWidget(self.label_number_reaction_description, 4, 0, 1, 1)
        self.label_number_metabolites_description = QtWidgets.QLabel(self.informationBox)
        self.label_number_metabolites_description.setObjectName("label_number_metabolites_description")
        self.gridLayout.addWidget(self.label_number_metabolites_description, 3, 0, 1, 1)
        self.label_model_path_description = QtWidgets.QLabel(self.informationBox)
        self.label_model_path_description.setObjectName("label_model_path_description")
        self.gridLayout.addWidget(self.label_model_path_description, 0, 0, 1, 1)
        self.label_model_id = QtWidgets.QLabel(self.informationBox)
        self.label_model_id.setText("")
        self.label_model_id.setObjectName("label_model_id")
        self.gridLayout.addWidget(self.label_model_id, 1, 1, 1, 1)
        self.label_model_id_description = QtWidgets.QLabel(self.informationBox)
        self.label_model_id_description.setObjectName("label_model_id_description")
        self.gridLayout.addWidget(self.label_model_id_description, 1, 0, 1, 1)
        self.label_number_genes = QtWidgets.QLabel(self.informationBox)
        self.label_number_genes.setText("")
        self.label_number_genes.setObjectName("label_number_genes")
        self.gridLayout.addWidget(self.label_number_genes, 5, 1, 1, 1)
        self.label_compartment_description = QtWidgets.QLabel(self.informationBox)
        self.label_compartment_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_compartment_description.setObjectName("label_compartment_description")
        self.gridLayout.addWidget(self.label_compartment_description, 6, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.informationBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setMinimumSize(QtCore.QSize(40, 40))
        self.tableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setDefaultSectionSize(60)
        self.tableView.horizontalHeader().setHighlightSections(False)
        self.tableView.horizontalHeader().setMinimumSectionSize(60)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.tableView.verticalHeader().setDefaultSectionSize(25)
        self.tableView.verticalHeader().setMinimumSectionSize(25)
        self.gridLayout.addWidget(self.tableView, 6, 1, 1, 1)
        self.label_model_name_description = QtWidgets.QLabel(self.informationBox)
        self.label_model_name_description.setObjectName("label_model_name_description")
        self.gridLayout.addWidget(self.label_model_name_description, 2, 0, 1, 1)
        self.label_model_name = QtWidgets.QLabel(self.informationBox)
        self.label_model_name.setText("")
        self.label_model_name.setObjectName("label_model_name")
        self.gridLayout.addWidget(self.label_model_name, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.informationBox, 0, 0, 1, 1)

        self.retranslateUi(modelDisaplayWidget)
        QtCore.QMetaObject.connectSlotsByName(modelDisaplayWidget)

    def retranslateUi(self, modelDisaplayWidget):
        _translate = QtCore.QCoreApplication.translate
        modelDisaplayWidget.setWindowTitle(_translate("modelDisaplayWidget", "Form"))
        self.informationBox.setTitle(_translate("modelDisaplayWidget", "Model information"))
        self.label_number_genes_description.setText(_translate("modelDisaplayWidget", "Genes:"))
        self.label_number_reaction_description.setText(_translate("modelDisaplayWidget", "Reactions:"))
        self.label_number_metabolites_description.setText(_translate("modelDisaplayWidget", "Metabolites:"))
        self.label_model_path_description.setText(_translate("modelDisaplayWidget", "Path:"))
        self.label_model_id_description.setText(_translate("modelDisaplayWidget", "ID:"))
        self.label_compartment_description.setText(_translate("modelDisaplayWidget", "Compartments:"))
        self.label_model_name_description.setText(_translate("modelDisaplayWidget", "Name:"))

