# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BatchEvidenceDialog.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BatchEvidenceDialog(object):
    def setupUi(self, BatchEvidenceDialog):
        BatchEvidenceDialog.setObjectName("BatchEvidenceDialog")
        BatchEvidenceDialog.resize(554, 484)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(BatchEvidenceDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(BatchEvidenceDialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboBox_type = QtWidgets.QComboBox(BatchEvidenceDialog)
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_type)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(BatchEvidenceDialog)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(BatchEvidenceDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_missing = QtWidgets.QComboBox(BatchEvidenceDialog)
        self.comboBox_missing.setObjectName("comboBox_missing")
        self.comboBox_missing.addItem("")
        self.comboBox_missing.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_missing)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(BatchEvidenceDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_assertion = QtWidgets.QLabel(BatchEvidenceDialog)
        self.label_assertion.setText("")
        self.label_assertion.setObjectName("label_assertion")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_assertion)
        self.label_4 = QtWidgets.QLabel(BatchEvidenceDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_eco = QtWidgets.QLabel(BatchEvidenceDialog)
        self.label_eco.setText("")
        self.label_eco.setObjectName("label_eco")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_eco)
        self.label_6 = QtWidgets.QLabel(BatchEvidenceDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_target = QtWidgets.QLabel(BatchEvidenceDialog)
        self.label_target.setText("")
        self.label_target.setObjectName("label_target")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_target)
        self.label_8 = QtWidgets.QLabel(BatchEvidenceDialog)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.textBrowser_comment = QtWidgets.QTextBrowser(BatchEvidenceDialog)
        self.textBrowser_comment.setObjectName("textBrowser_comment")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.textBrowser_comment)
        self.pushButton = QtWidgets.QPushButton(BatchEvidenceDialog)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.label_9 = QtWidgets.QLabel(BatchEvidenceDialog)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.listWidget_referencees = QtWidgets.QListWidget(BatchEvidenceDialog)
        self.listWidget_referencees.setObjectName("listWidget_referencees")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.listWidget_referencees)
        self.horizontalLayout_4.addLayout(self.formLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.buttonBox = QtWidgets.QDialogButtonBox(BatchEvidenceDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(BatchEvidenceDialog)
        self.buttonBox.accepted.connect(BatchEvidenceDialog.accept)
        self.buttonBox.rejected.connect(BatchEvidenceDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(BatchEvidenceDialog)

    def retranslateUi(self, BatchEvidenceDialog):
        _translate = QtCore.QCoreApplication.translate
        BatchEvidenceDialog.setWindowTitle(_translate("BatchEvidenceDialog", "Add evidences"))
        self.label_3.setText(_translate("BatchEvidenceDialog", "Type:"))
        self.comboBox_type.setItemText(0, _translate("BatchEvidenceDialog", "Gene"))
        self.label.setText(_translate("BatchEvidenceDialog", "Missing:"))
        self.comboBox_missing.setItemText(0, _translate("BatchEvidenceDialog", "Add"))
        self.comboBox_missing.setItemText(1, _translate("BatchEvidenceDialog", "Ignore"))
        self.label_2.setText(_translate("BatchEvidenceDialog", "Assertion:"))
        self.label_4.setText(_translate("BatchEvidenceDialog", "ECO:"))
        self.label_6.setText(_translate("BatchEvidenceDialog", "Target:"))
        self.label_8.setText(_translate("BatchEvidenceDialog", "Comment:"))
        self.pushButton.setText(_translate("BatchEvidenceDialog", "Edit Evidence"))
        self.label_9.setText(_translate("BatchEvidenceDialog", "References:"))

