# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\EditEvidenceDialog.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EditEvidenceDialog(object):
    def setupUi(self, EditEvidenceDialog):
        EditEvidenceDialog.setObjectName("EditEvidenceDialog")
        EditEvidenceDialog.resize(278, 321)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(EditEvidenceDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(EditEvidenceDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.evidenceTab = QtWidgets.QWidget()
        self.evidenceTab.setObjectName("evidenceTab")
        self.gridLayout = QtWidgets.QGridLayout(self.evidenceTab)
        self.gridLayout.setObjectName("gridLayout")
        self.combo_assertion = QtWidgets.QComboBox(self.evidenceTab)
        self.combo_assertion.setObjectName("combo_assertion")
        self.gridLayout.addWidget(self.combo_assertion, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.evidenceTab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_eco = QtWidgets.QLabel(self.evidenceTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_eco.sizePolicy().hasHeightForWidth())
        self.label_eco.setSizePolicy(sizePolicy)
        self.label_eco.setText("")
        self.label_eco.setWordWrap(True)
        self.label_eco.setObjectName("label_eco")
        self.horizontalLayout_2.addWidget(self.label_eco)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.button_select_eco = QtWidgets.QPushButton(self.evidenceTab)
        self.button_select_eco.setObjectName("button_select_eco")
        self.horizontalLayout_2.addWidget(self.button_select_eco)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_target = QtWidgets.QLabel(self.evidenceTab)
        self.label_target.setText("")
        self.label_target.setObjectName("label_target")
        self.horizontalLayout_3.addWidget(self.label_target)
        self.toolbutton_select_target = QtWidgets.QToolButton(self.evidenceTab)
        self.toolbutton_select_target.setIconSize(QtCore.QSize(13, 13))
        self.toolbutton_select_target.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.toolbutton_select_target.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolbutton_select_target.setArrowType(QtCore.Qt.RightArrow)
        self.toolbutton_select_target.setObjectName("toolbutton_select_target")
        self.horizontalLayout_3.addWidget(self.toolbutton_select_target)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.evidenceTab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.evidenceTab)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.tabWidget.addTab(self.evidenceTab, "")
        self.referenceTab = QtWidgets.QWidget()
        self.referenceTab.setObjectName("referenceTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.referenceTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.referenceWidget = ReferenceDisplayWidget(self.referenceTab)
        self.referenceWidget.setObjectName("referenceWidget")
        self.verticalLayout_3.addWidget(self.referenceWidget)
        self.tabWidget.addTab(self.referenceTab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.groupBox = QtWidgets.QGroupBox(EditEvidenceDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBox_comment = QtWidgets.QPlainTextEdit(self.groupBox)
        self.textBox_comment.setObjectName("textBox_comment")
        self.verticalLayout.addWidget(self.textBox_comment)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(EditEvidenceDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(EditEvidenceDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(EditEvidenceDialog.accept)
        self.buttonBox.rejected.connect(EditEvidenceDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(EditEvidenceDialog)

    def retranslateUi(self, EditEvidenceDialog):
        _translate = QtCore.QCoreApplication.translate
        EditEvidenceDialog.setWindowTitle(_translate("EditEvidenceDialog", "Edit Evidence"))
        self.label.setText(_translate("EditEvidenceDialog", "Assertion:"))
        self.button_select_eco.setText(_translate("EditEvidenceDialog", "Select"))
        self.toolbutton_select_target.setText(_translate("EditEvidenceDialog", "Select"))
        self.label_3.setText(_translate("EditEvidenceDialog", "Target:"))
        self.label_2.setText(_translate("EditEvidenceDialog", "Code:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.evidenceTab), _translate("EditEvidenceDialog", "Evidence"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.referenceTab), _translate("EditEvidenceDialog", "References"))
        self.groupBox.setTitle(_translate("EditEvidenceDialog", "Comment"))


from GEMEditor.model.display.reference import ReferenceDisplayWidget
