# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\EditReferenceDialog.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ReferenceEditDialog(object):
    def setupUi(self, ReferenceEditDialog):
        ReferenceEditDialog.setObjectName("ReferenceEditDialog")
        ReferenceEditDialog.resize(291, 320)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ReferenceEditDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_authors = QtWidgets.QLabel(ReferenceEditDialog)
        self.label_authors.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_authors.setObjectName("label_authors")
        self.gridLayout.addWidget(self.label_authors, 0, 0, 1, 1)
        self.authorTableView = ElementTableView(ReferenceEditDialog)
        self.authorTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.authorTableView.setObjectName("authorTableView")
        self.authorTableView.horizontalHeader().setStretchLastSection(True)
        self.authorTableView.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.authorTableView, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.addAuthorButton = QtWidgets.QPushButton(ReferenceEditDialog)
        self.addAuthorButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/add_icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addAuthorButton.setIcon(icon)
        self.addAuthorButton.setObjectName("addAuthorButton")
        self.verticalLayout.addWidget(self.addAuthorButton)
        self.removeAuthorButton = QtWidgets.QPushButton(ReferenceEditDialog)
        self.removeAuthorButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/remove_icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeAuthorButton.setIcon(icon1)
        self.removeAuthorButton.setObjectName("removeAuthorButton")
        self.verticalLayout.addWidget(self.removeAuthorButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 1, 1)
        self.label_title = QtWidgets.QLabel(ReferenceEditDialog)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 1, 0, 1, 1)
        self.titleInput = QtWidgets.QLineEdit(ReferenceEditDialog)
        self.titleInput.setObjectName("titleInput")
        self.gridLayout.addWidget(self.titleInput, 1, 1, 1, 2)
        self.label_year = QtWidgets.QLabel(ReferenceEditDialog)
        self.label_year.setObjectName("label_year")
        self.gridLayout.addWidget(self.label_year, 2, 0, 1, 1)
        self.yearInput = QtWidgets.QLineEdit(ReferenceEditDialog)
        self.yearInput.setObjectName("yearInput")
        self.gridLayout.addWidget(self.yearInput, 2, 1, 1, 2)
        self.label_journal = QtWidgets.QLabel(ReferenceEditDialog)
        self.label_journal.setObjectName("label_journal")
        self.gridLayout.addWidget(self.label_journal, 3, 0, 1, 1)
        self.journalInput = QtWidgets.QLineEdit(ReferenceEditDialog)
        self.journalInput.setObjectName("journalInput")
        self.gridLayout.addWidget(self.journalInput, 3, 1, 1, 2)
        self.label_pmid = QtWidgets.QLabel(ReferenceEditDialog)
        self.label_pmid.setObjectName("label_pmid")
        self.gridLayout.addWidget(self.label_pmid, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pmidInput = QtWidgets.QLineEdit(ReferenceEditDialog)
        self.pmidInput.setObjectName("pmidInput")
        self.horizontalLayout.addWidget(self.pmidInput)
        self.searchPubmedButton = QtWidgets.QPushButton(ReferenceEditDialog)
        self.searchPubmedButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/search_icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchPubmedButton.setIcon(icon2)
        self.searchPubmedButton.setObjectName("searchPubmedButton")
        self.horizontalLayout.addWidget(self.searchPubmedButton)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 1, 1, 2)
        self.label_pmc = QtWidgets.QLabel(ReferenceEditDialog)
        self.label_pmc.setObjectName("label_pmc")
        self.gridLayout.addWidget(self.label_pmc, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pmcInput = QtWidgets.QLineEdit(ReferenceEditDialog)
        self.pmcInput.setObjectName("pmcInput")
        self.horizontalLayout_2.addWidget(self.pmcInput)
        self.searchPMCButton = QtWidgets.QPushButton(ReferenceEditDialog)
        self.searchPMCButton.setText("")
        self.searchPMCButton.setIcon(icon2)
        self.searchPMCButton.setObjectName("searchPMCButton")
        self.horizontalLayout_2.addWidget(self.searchPMCButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 1, 1, 2)
        self.label_doi = QtWidgets.QLabel(ReferenceEditDialog)
        self.label_doi.setObjectName("label_doi")
        self.gridLayout.addWidget(self.label_doi, 6, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.doiInput = QtWidgets.QLineEdit(ReferenceEditDialog)
        self.doiInput.setObjectName("doiInput")
        self.horizontalLayout_3.addWidget(self.doiInput)
        self.searchDOIButton = QtWidgets.QPushButton(ReferenceEditDialog)
        self.searchDOIButton.setText("")
        self.searchDOIButton.setIcon(icon2)
        self.searchDOIButton.setObjectName("searchDOIButton")
        self.horizontalLayout_3.addWidget(self.searchDOIButton)
        self.gridLayout.addLayout(self.horizontalLayout_3, 6, 1, 1, 2)
        self.label_link = QtWidgets.QLabel(ReferenceEditDialog)
        self.label_link.setObjectName("label_link")
        self.gridLayout.addWidget(self.label_link, 7, 0, 1, 1)
        self.linkInput = QtWidgets.QLineEdit(ReferenceEditDialog)
        self.linkInput.setObjectName("linkInput")
        self.gridLayout.addWidget(self.linkInput, 7, 1, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(ReferenceEditDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(ReferenceEditDialog)
        self.buttonBox.accepted.connect(ReferenceEditDialog.accept)
        self.buttonBox.rejected.connect(ReferenceEditDialog.reject)
        self.titleInput.textEdited['QString'].connect(ReferenceEditDialog.activateButton)
        self.yearInput.textEdited['QString'].connect(ReferenceEditDialog.activateButton)
        self.journalInput.textEdited['QString'].connect(ReferenceEditDialog.activateButton)
        self.pmidInput.textEdited['QString'].connect(ReferenceEditDialog.activateButton)
        self.pmcInput.textEdited['QString'].connect(ReferenceEditDialog.activateButton)
        self.doiInput.textEdited['QString'].connect(ReferenceEditDialog.activateButton)
        self.linkInput.textEdited['QString'].connect(ReferenceEditDialog.activateButton)
        self.addAuthorButton.clicked.connect(ReferenceEditDialog.addAuthor)
        self.removeAuthorButton.clicked.connect(ReferenceEditDialog.deleteAuthor)
        self.searchPubmedButton.clicked.connect(ReferenceEditDialog.getPmidInfo)
        self.searchPMCButton.clicked.connect(ReferenceEditDialog.checkPMC)
        self.pmidInput.textEdited['QString'].connect(ReferenceEditDialog.checkPMID)
        self.pmcInput.textEdited['QString'].connect(ReferenceEditDialog.checkPMC)
        ReferenceEditDialog.accepted.connect(ReferenceEditDialog.save_state)
        self.searchPMCButton.clicked.connect(ReferenceEditDialog.getPmcInfo)
        self.searchDOIButton.clicked.connect(ReferenceEditDialog.getDOIInfo)
        ReferenceEditDialog.finished['int'].connect(ReferenceEditDialog.save_dialog_geometry)
        QtCore.QMetaObject.connectSlotsByName(ReferenceEditDialog)
        ReferenceEditDialog.setTabOrder(self.authorTableView, self.yearInput)
        ReferenceEditDialog.setTabOrder(self.yearInput, self.journalInput)
        ReferenceEditDialog.setTabOrder(self.journalInput, self.pmidInput)
        ReferenceEditDialog.setTabOrder(self.pmidInput, self.searchPubmedButton)
        ReferenceEditDialog.setTabOrder(self.searchPubmedButton, self.pmcInput)
        ReferenceEditDialog.setTabOrder(self.pmcInput, self.searchPMCButton)
        ReferenceEditDialog.setTabOrder(self.searchPMCButton, self.doiInput)
        ReferenceEditDialog.setTabOrder(self.doiInput, self.linkInput)
        ReferenceEditDialog.setTabOrder(self.linkInput, self.addAuthorButton)
        ReferenceEditDialog.setTabOrder(self.addAuthorButton, self.removeAuthorButton)

    def retranslateUi(self, ReferenceEditDialog):
        _translate = QtCore.QCoreApplication.translate
        ReferenceEditDialog.setWindowTitle(_translate("ReferenceEditDialog", "Edit Reference"))
        self.label_authors.setText(_translate("ReferenceEditDialog", "Authors:"))
        self.label_title.setText(_translate("ReferenceEditDialog", "Title:"))
        self.label_year.setText(_translate("ReferenceEditDialog", "Year:"))
        self.label_journal.setText(_translate("ReferenceEditDialog", "Journal:"))
        self.label_pmid.setText(_translate("ReferenceEditDialog", "PMID:"))
        self.label_pmc.setText(_translate("ReferenceEditDialog", "PMC:"))
        self.label_doi.setText(_translate("ReferenceEditDialog", "DOI:"))
        self.label_link.setText(_translate("ReferenceEditDialog", "Link"))

from GEMEditor.base.views import ElementTableView
import icons_rc
