# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MetaboliteEntryDisplayWidget.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MetaboliteEntryDisplayWidget(object):
    def setupUi(self, MetaboliteEntryDisplayWidget):
        MetaboliteEntryDisplayWidget.setObjectName("MetaboliteEntryDisplayWidget")
        MetaboliteEntryDisplayWidget.resize(333, 465)
        self.formLayout = QtWidgets.QFormLayout(MetaboliteEntryDisplayWidget)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(MetaboliteEntryDisplayWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_name = QtWidgets.QLabel(MetaboliteEntryDisplayWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        self.label_name.setText("")
        self.label_name.setWordWrap(True)
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_name)
        self.label_4 = QtWidgets.QLabel(MetaboliteEntryDisplayWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_formula = QtWidgets.QLabel(MetaboliteEntryDisplayWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_formula.sizePolicy().hasHeightForWidth())
        self.label_formula.setSizePolicy(sizePolicy)
        self.label_formula.setText("")
        self.label_formula.setObjectName("label_formula")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_formula)
        self.label_2 = QtWidgets.QLabel(MetaboliteEntryDisplayWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_charge = QtWidgets.QLabel(MetaboliteEntryDisplayWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_charge.sizePolicy().hasHeightForWidth())
        self.label_charge.setSizePolicy(sizePolicy)
        self.label_charge.setText("")
        self.label_charge.setObjectName("label_charge")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_charge)
        self.label_3 = QtWidgets.QLabel(MetaboliteEntryDisplayWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.list_synonyms = QtWidgets.QListWidget(MetaboliteEntryDisplayWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_synonyms.sizePolicy().hasHeightForWidth())
        self.list_synonyms.setSizePolicy(sizePolicy)
        self.list_synonyms.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.list_synonyms.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_synonyms.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.list_synonyms.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.list_synonyms.setObjectName("list_synonyms")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.list_synonyms)
        self.label_5 = QtWidgets.QLabel(MetaboliteEntryDisplayWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.table_identifiers = AnnotationTableWidget(MetaboliteEntryDisplayWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_identifiers.sizePolicy().hasHeightForWidth())
        self.table_identifiers.setSizePolicy(sizePolicy)
        self.table_identifiers.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.table_identifiers.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_identifiers.setWordWrap(False)
        self.table_identifiers.setObjectName("table_identifiers")
        self.table_identifiers.setColumnCount(0)
        self.table_identifiers.setRowCount(0)
        self.table_identifiers.horizontalHeader().setStretchLastSection(True)
        self.table_identifiers.verticalHeader().setVisible(False)
        self.table_identifiers.verticalHeader().setHighlightSections(False)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.table_identifiers)

        self.retranslateUi(MetaboliteEntryDisplayWidget)
        QtCore.QMetaObject.connectSlotsByName(MetaboliteEntryDisplayWidget)

    def retranslateUi(self, MetaboliteEntryDisplayWidget):
        _translate = QtCore.QCoreApplication.translate
        MetaboliteEntryDisplayWidget.setWindowTitle(_translate("MetaboliteEntryDisplayWidget", "Form"))
        self.label.setText(_translate("MetaboliteEntryDisplayWidget", "Name:"))
        self.label_4.setText(_translate("MetaboliteEntryDisplayWidget", "Formula:"))
        self.label_2.setText(_translate("MetaboliteEntryDisplayWidget", "Charge:"))
        self.label_3.setText(_translate("MetaboliteEntryDisplayWidget", "Synonyms:"))
        self.label_5.setText(_translate("MetaboliteEntryDisplayWidget", "Identifier:"))

from GEMEditor.base.widgets import AnnotationTableWidget
